// <auto-generated />
namespace VidlyTutorial.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _02122019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_02122019));
        
        string IMigrationMetadata.Id
        {
            get { return "201912021342224_02-12-2019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
